
int-const               = 1*DIGIT / '0x' 1*HEXDIG

char-const              = "'" VCHAR "'"

float-const             = 1*DIGIT [ '.' 1*DIGIT ]

id-char                 = ALPHA / DIGIT / '_'

id                      = ( ALPHA / '_' ) *id-char 

string                  = DQUOTE *ALPHA DQUOTE

enumeration-const       = id

