; comment

bareword          =  [ '-' ] ( ALPHA / '_' ) *( ALPHA / DIGIT / '_' ) 

key               =  bareword / string / number

escape            =  '\"' / '\n' / '\t' / '\r' / '\x' HEXDIG HEXDIG
string-safe-char  =  %x20-21 / %x23-5b / %x5d-7e
string-char       =  string-safe-char / escape
string            =  DQUOTE *string-char DQUOTE

posint            =  '0' / ( %x31-39 *DIGIT )
number            =  [ '-' ] posint [ '.' 1*DIGIT ] [ 'E' ( '+' / '-' / '' ) posint ]

scalar            =  number / string / 'undef'
value             =  array / hash / scalar
array             =  '[' value *( ', ' value ) ']'
key-value         =  key ' => ' value
key-value         =/ ( string / number ) ', ' value
hash              =  '{' key-value *( ', ' key-value ) '}'

perl              =  value
